jobs:
- job: Windows
  pool:
    name: Hosted VS2017
    demands: npm
  steps:
  - task: NodeTool@0
    displayName: 'Use Node 10.x'
    inputs:
      versionSpec: 10.x
  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      verbose: false
  - task: Npm@1
    displayName: 'Compile sources'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run compile'
  - script: 'npm run test-unit'
    displayName: 'Run unit tests'
  - script: 'npm run test-integration'
    displayName: 'Run integration tests'
  - script: 'npm run lint'
    displayName: 'Run linting'
- job: macOS
  pool:
    name: Hosted macOS
    demands: npm
  steps:
  - task: NodeTool@0
    displayName: 'Use Node 10.x'
    inputs:
      versionSpec: 10.x
  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      verbose: false
  - task: Npm@1
    displayName: 'Compile sources'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run compile'
  - script: 'npm run test-unit'
    displayName: 'Run unit tests'
  - script: 'npm run test-integration'
    displayName: 'Run integration tests'
  - script: 'npm run lint'
    displayName: 'Run linting'
- job: Linux
  pool:
    name: Hosted Ubuntu 1604
    demands: npm
  steps:
  - task: NodeTool@0
    displayName: 'Use Node 10.x'
    inputs:
      versionSpec: 10.x
  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      verbose: false
  - task: Npm@1
    displayName: 'Compile sources'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run compile'
  - script: |
      set -e
      /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
      disown -ar
    displayName: 'Start xvfb'
  - script: 'npm run test-unit'
    displayName: 'Run unit tests'
    env:
      DISPLAY: :10
  - script: 'npm run test-integration'
    displayName: 'Run integration tests'
    env:
      DISPLAY: :10
  - script: 'npm run lint'
    displayName: 'Run linting'
    env:
      DISPLAY: :10
