name: Continuous Integration
on:
  schedule:
    # Weekly on Mondays for Windows / Mac
    - cron: '0 0 * * 1'
    # Nightly builds for Linux (cheapest)
    - cron: '0 0 * * *'
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    if: |
      github.event_name != 'schedule' ||
      (github.event.schedule == '0 0 * * *' && matrix.os == 'ubuntu-latest') ||
      (github.event.schedule == '0 0 * * 1' && matrix.os != 'ubuntu-latest')
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: npm install
    - run: npm run build
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'