name: Continuous Integration
on:
  schedule:
    # Weekly on Mondays for Windows / Mac
    - cron: '0 15 * * 1'
      timezone: 'America/Vancouver'
    # Nightly builds for Linux (cheapest)
    - cron: '0 15 * * *'
      timezone: 'America/Vancouver'
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Run test suite
      # Properly considers the following use cases:
      # 1) Manual action run
      # 2) Weekly scheduled run for Mac and Windows
      # 3) Nightly scheduled run for Linux
      if: github.event_name != 'schedule' || (github.event.schedule == '30 14 * * 1' && matrix.os != 'ubuntu-latest') || (github.event.schedule == '30 14 * * *' && matrix.os == 'ubuntu-latest')
      uses: ./.github/workflows/run_tests.yml
      with:
        runner-type: ${{ matrix.os }}
