name: Continuous Integration
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: npm install
    - run: npm run build
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: |
        for i in {1..3}; do
          npm test
          if [ $i -eq 3 ]; then
            echo "Command failed after 3 attempts."
            exit 1
          fi
        done
      if: runner.os != 'Linux'
